using ExcelFlow.Worker.Consumers;
using ExcelFlow.Web.Common.Extensions;
using ExcelFlow.Services.Interfaces;
using ExcelFlow.Services.Services;
using ExcelFlow.Core.Interfaces;
using ExcelFlow.DataAccess.Repositories;
var builder = Host.CreateApplicationBuilder(args);
builder.Configuration.AddDefaultAppSettings();
builder.Services.AddHostedService<ExcelMessageConsumer>();
builder.Services.AddScoped<IExcelProcessorService, ExcelProcessorService>();
builder.Services.AddScoped<IUploadJobService, UploadJobService>();
builder.Services.AddScoped<IUploadJobRepository, UploadJobRepository>();
builder.Services.AddScoped<IExcelValidationEngine, ExcelValidationEngine>();
builder.Services.AddScoped<IExcelTemplateService, ExcelTemplateService>();
builder.Services.AddScoped<IExcelTemplateRepository, ExcelTemplateRepository>();
builder.Services.AddScoped<IExcelValidationRepository, ExcelValidationRepository>();
builder.Services.AddScoped<IExcelReaderService, ExcelReaderService>();
builder.Services.AddScoped<IUploadJobErrorService, UploadJobErrorService>();
builder.Services.AddScoped<IExcelMapperService, ExcelMapperService>();
builder.Services.AddExcelFlowServices(builder.Configuration);
var host = builder.Build();
host.Run();
